export const OrderTypeOptions = ["Multi Fam", "Single Fam", "Reno"];
export const FinishOptions = ["Glaze", "STD", "N/A"];
export const DoorStyleOptions = [
  `1 1/4" Rail Shaker Flat Panel  `,
  `1 3/4 MINIMAL SHAKER  `,
  `1/2" Slim Shaker  `,
  `1PC-SHAKER-FP  `,
  `2" Rail Shaker FP  `,
  `2" Rail Square FP  `,
  `2171`,
  `3" M588  `,
  `3" Rail Arch Flat Panel  `,
  `3" Rail Arch Raised Panel  `,
  `3" Rail Shaker Bead Panel  `,
  `3" Rail Shaker Flat Panel`,
  `3" Rail Shaker Raised Panel  `,
  `3" Rail Shaker Reverse Panel  `,
  `3" Rail Square Flat Panel  `,
  `3" Rail Square Raised Panel  `,
  `3" Rail V-Groove Raised Flat Panel  `,
  `3" Rail V-Groove Shaker Flat Panel  `,
  `3" Rail VGroove Shaker Raised Panel  `,
  `3/4" Rail Shaker Flat Panel  `,
  `3/4" Rail Slim Shaker  `,
  `588 Shaker Flat Panel  `,
  `588-01 shaker flat panel  `,
  `Aspen Profile  `,
  `Bevel Shaker Flat Panel`,
  `BRERA  `,
  `Cathedral Flat Panel  `,
  `Cathedral Raised Panel  `,
  `CL4459  `,
  `CL4536  `,
  `CL4546  `,
  `Colonial  `,
  `Custom  `,
  `Custom Flat Panel  `,
  `Custom Raised Panel  `,
  `Daisy  `,
  `Flat Panel 992P Special  `,
  `flat panel 992P Special/regular edge  `,
  `GAMMA  `,
  `Glass Shaker Flat Panel`,
  `Half Moon Flat Panel  `,
  `Half Moon Raised Panel  `,
  `M03 Raised Panel  `,
  `M11 Raised Panel  `,
  `M11 Raised Panel #7 outside Edge  `,
  `M2 Flat Panel  `,
  `M4 Flat Panel (3and4 Rail)  `,
  `M4 Raised Panel  `,
  `M40 Flat Panel  `,
  `m44  `,
  `M44-1  `,
  `M53 with 18 Edge  `,
  `M588 #10 Edge`,
  `M588 Special FP Regular Edge  `,
  `M588 with Regular Edge  `,
  `M588-1  `,
  `M588-FP2 EDGE  `,
  `M612  `,
  `M619  `,
  `M70 Flat Panel  `,
  `M702  `,
  `M89  `,
  `M89-1  `,
  `M94 Flat Panel  `,
  `M94 w Bevel Edge  `,
  `ML-4300  `,
  `ML-4459`,
  `ML-4546`,
  `ML-4741`,
  `ML4459`,
  `ml4935`,
  `MN1`,
  `MN1 Flat Panel`,
  `MN1 Mitre Flat Panel`,
  `MN3 Mitre Flat Panel `,
  `MN3 Mitre Raised Panel`,
  `MN3 Mitre with Glass Panel`,
  `MR1 Flat Panel`,
  `MR3 Raised Panel`,
  `MRP Raised Panel`,
  `MV32VP`,
  `MW1 Flat Panel`,
  `MX3 Raise`,
  `MX3 Raised Panel`,
  `N/A`,
  `Pillow Soft Rail Flat Panel`,
  `Pillow Soft Rail Raised Panel`,
  `Premoule `,
  `RAISED S`,
  `Rosemary`,
  `RS21 Raised panel `,
  `Sample Doors`,
  `Shaker`,
  `Shaker Beaded Reversed Panel`,
  `SHAKER CL4459`,
  `Shaker Flat Panel`,
  `shaker flat panel 588-01`,
  `Shaker FP & Shaker VP FP`,
  `Shaker FP w/ Mid Rail`,
  `Shaker Raised Panel`,
  `Shaker Reverse Raised Beaded Panel`,
  `shaker reversed raised panel`,
  `Shaker V Groove Beaded Panel (MDF)`,
  `SHAKER V-GROOVE FLAT PANEL`,
  `Shaker V-Groove Glass Panel`,
  `Shaker V-Groove Reverse Raised Panel`,
  `Shaker V-Groove VP Panel`,
  `shaker vp flat panel`,
  `Shaker VP Reverse Raised Panel`,
  `Shaker w Mullion`,
  `Shaker with Speaker Cloth`,
  `SHAKER-3 PANEL`,
  `shaker-inside bevel-see joe`,
  `Shiplap Door`,
  `SLAB`,
  `slab 90 degree side wrap`,
  `Slab Panel`,
  `Slab with #11 Outer Edge`,
  `SLIM`,
  `Slim Shaker`,
  `Slim Shaker M685 MDF`,
  `Slim Shaker Ply78`,
  `Square Flat Panel`,
  `Square Pillow Flat Panel`,
  `Square Raised Panel`,
  `square rev raised VP panel`,
  `Square Reversed Raised Panel`,
  `TF614 Shaker Flat Panel`,
  `TF624-Shaker V-Groove Flat Panel`,
  `TF626 Raised panel`,
  `V-Groove Reverse Raised Beaded Panel`,
  `V-Groove Shaker Flat Panel`,
  `V-Groove Shaker Glass`,
  `V-Groove Shaker Raised Panel`,
  `V-Groove Shaker VP Panel`,
];

export const TopDrawerFrontOptions = ["5 pc", "Matching", "Slab"];
export const InteriorOptions = [
  "Almond",
  "Birch",
  "Grey",
  "Maple Ply",
  "N/A",
  "Photo Mpl",
  "White Mel",
  "White Ply",
  "Fin Int",
];
export const DrawerBoxOptions = [
  "Std",
  "Dbl Wall",
  "Metal Box",
  "Mpl Dove",
  "Birch F/J",
];
export const DrawerHardwareOptions = [
  "Std",
  "Dbl Wall",
  "Metal Box",
  "SC Under",
  "F/X Side",
];
export const DeliveryTypeOptions = ["Pickup", "Delivery"];
export const flooringTypeOptions = [
  "Hardwood",
  "Laminate",
  "Lino",
  "Tile",
  "Other",
];
export const flooringClearanceOptions = [
  `3/8"`,
  `1/2"`,
  `5/8"`,
  `3/4"`,
  `7/8"`,
  `1"`,
  "TBD",
];
