create table if not exists "public"."backorders" (
    "id" bigint generated by default as identity not null primary key,
    "job_id" bigint not null references "public"."jobs"("id") on delete cascade,
    "date_entered" date default current_date,
    "due_date" date,
    "comments" text,
    "complete" boolean default false not null,
    "created_at" timestamp with time zone default now() not null
)