-- Create the invoices table
create table public.invoices (
  invoice_id bigint generated by default as identity primary key, 
  invoice_number text,
  job_id bigint not null references public.jobs(id) on delete cascade,
  date_entered date default current_date,
  date_due date,
  paid_at timestamptz, 
  no_charge boolean default false,
  comments text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
