-- 1. Service Orders Table
create table if not exists service_orders (
  service_order_id bigint generated by default as identity primary key,
  job_id bigint not null references jobs(id) on delete cascade,
  service_order_number text not null unique,
  date_entered timestamptz not null default now(),
  due_date date,
  completed_at timestamptz,
  installer_id integer references installers(installer_id) on delete set null,
  service_type text null,
  service_by text null,
  hours_estimated integer null
);

-- 2. Service Order Parts Table
create table if not exists service_order_parts (
  id bigint generated by default as identity primary key,
  service_order_id bigint not null references service_orders(service_order_id) on delete cascade,
  qty integer NOT NULL DEFAULT 1,
  part text not null,
  description text 
);